<?php

return [
    'Vietcombank',
    'BIDV',
    'VietinBank',
    'Agribank',
    'MB Bank',
    'Techcombank',
    'ACB',
    'VPBank',
    'TPBank',
    'Sacombank',
    'HDBank',
    'VIB',
    'SHB',
    'SeABank',
    'OCB',
    'MSB',
    'Eximbank',
    'LienVietPostBank',
    'PVcomBank',
    'Bac A Bank',
    'Nam A Bank',
    'ABBANK',
    'VietABank',
    'BaoViet Bank',
    'NCB',
    'KienlongBank',
    'PG Bank',
    'Saigonbank',
    'DongA Bank',
    'Shinhan Bank',
    'Hong Leong Bank',
    'Standard Chartered',
    'CIMB',
    'Woori Bank',
    'UOB',
    'HSBC',
];
